export const cardsContent = [
  {
    id: 1,
    image: '../imgs/Twitch.jpg',
    title: 'Twitch',
    tag: '@afkdude',
    background: '#6441A5',
    colorText: '#FFF',
    colorBorder: '#B691FB',
    contentBtn: 'Follow',
    Zindex: 10,
  },
  {
    id: 2,
    image: '../imgs/Roblox.jpg',
    title: 'Roblox',
    tag: '@diego#gt',
    background: '#000',
    colorText: '#FFF',
    colorBorder: '#B3AEBB',
    contentBtn: 'Stats',
    Zindex: 6,
  },
  {
    id: 3,
    image: '../imgs/instagram.jpeg',
    title: 'Instagram',
    tag: '@foxxie',
    background:
      'linear-gradient(180deg, #515BD4 0%, #8134AF 33.33%, #DD2A7B 66.67%, #FEDA77 100%)',
    colorText: '#FFF',
    colorHeart: '#5559D2',
    colorBorder: '#FCCD78',
    contentBtn: 'Follow',
    ColorTextBtn: '#5559D2',
    Zindex: 7,
  },
  {
    id: 4,
    image: '../imgs/Fortnite.jpg',
    title: 'Fornite',
    tag: '@aurore91470',
    background: 'linear-gradient(180deg, #1B90DD 0%, #5FCEEA 100%)',
    colorText: '#FFF',
    colorBorder: '#1D91DE',
    contentBtn: 'Stats',
    Zindex: 6,
  },
  {
    id: 5,
    image: '../imgs/Minecraft.jpg',
    title: 'Minecraft',
    tag: '@builtParis',
    background: 'linear-gradient(180deg, #CEC2BE 0%, #A99E9B 100%)',
    colorText: '#000',
    colorBorder: '#CFC3BF',
    contentBtn: 'Stats',
    Zindex: 9,
  },
  {
    id: 6,
    image: '../imgs/Minecraft.jpg',
    title: 'Warzone',
    tag: '@234BG',
    background: '#000',
    colorText: '#FFF',
    colorBorder: '#000',
    contentBtn: 'Stats',
    Zindex: 10,
  },
  {
    id: 7,
    image: '../imgs/Snapchat.jpg',
    title: 'Snapchat',
    tag: '@hitmeup',
    background: '#FFFC00',
    colorText: '#000',

    colorHeart: '#FFF',
    colorBorder: '#FFF',
    contentBtn: 'Follow',
    ColorTextBtn: '#FFF',
    Zindex: 11,
  },
  {
    id: 8,
    title: 'This must be a joke',
    paragraph:
      'This must be a joke spawning in front of me and then hitting me back in a corner😒',
    background: '#0046AA',
    colorText: '#FFF',
    Zindex: 6,
    Height: '250px',
  },
];
